# Generated by Django 6.0.2

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_employmenthistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("clock_in_time", models.DateTimeField(blank=True, null=True)),
                ("clock_out_time", models.DateTimeField(blank=True, null=True)),
                ("total_work_hours", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("HALF_DAY", "Half Day"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_days",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workforce_attendanceday",
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.UniqueConstraint(
                fields=("employee", "date"),
                name="workforce_attendanceday_employee_date_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(fields=["employee", "date"], name="workforce_att_emp_date_idx"),
        ),
    ]
