# Generated by Django 6.0.2 on 2026-03-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendanceday',
            new_name='workforce_a_employe_9a7628_idx',
            old_name='workforce_att_emp_date_idx',
        ),
    ]
